package Arif180626;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-SI-PC
 */
public class FormMahasiswa extends javax.swing.JFrame {
    
    MahasiswaNilai mahasiswa = new MahasiswaNilai();
    MahasiswaNilaiController controller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
        controller = new MahasiswaNilaiController();
        tampilData();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNilaiTugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNilaiUts = new javax.swing.JTextField();
        txtNilaiUas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNilaiAngka = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNilaiHuruf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnProses = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        Cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NIM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 9, 60, 16);

        txtNIM.setText("jTextField1");
        getContentPane().add(txtNIM);
        txtNIM.setBounds(71, 6, 150, 22);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 37, 60, 16);

        txtNama.setText("jTextField1");
        getContentPane().add(txtNama);
        txtNama.setBounds(71, 34, 315, 22);

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 65, 60, 16);

        txtAlamat.setText("jTextField1");
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(73, 62, 313, 22);

        jLabel4.setText("Nilai Tugas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 93, 70, 16);

        txtNilaiTugas.setText("jTextField1");
        getContentPane().add(txtNilaiTugas);
        txtNilaiTugas.setBounds(73, 90, 313, 22);

        jLabel5.setText("Nilai UTS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 121, 59, 16);

        jLabel6.setText("Nilai UAS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 149, 59, 16);

        txtNilaiUts.setText("jTextField1");
        getContentPane().add(txtNilaiUts);
        txtNilaiUts.setBounds(71, 118, 315, 22);

        txtNilaiUas.setText("jTextField1");
        getContentPane().add(txtNilaiUas);
        txtNilaiUas.setBounds(71, 146, 315, 22);

        jLabel7.setText("Nilai Angka");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 10, 80, 16);

        txtNilaiAngka.setText("jTextField1");
        txtNilaiAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiAngkaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNilaiAngka);
        txtNilaiAngka.setBounds(460, 10, 210, 22);

        jLabel8.setText("Nilai Huruf");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 40, 58, 16);

        txtNilaiHuruf.setText("jTextField1");
        txtNilaiHuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNilaiHurufActionPerformed(evt);
            }
        });
        getContentPane().add(txtNilaiHuruf);
        txtNilaiHuruf.setBounds(460, 40, 210, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(85, 1, 72, 23);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Simpan);
        Simpan.setBounds(0, 0, 72, 23);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(70, -170, 452, 402);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 196, 380, 30);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(400, 70, 100, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Alamat", "Nilai Tugas", "Uts", "Nilai UAS", "Nilai Angka", "Nilai Huruf"
            }
        ));
        jScrollPane3.setViewportView(tabel);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 230, 660, 130);

        Cari.setText("Cari");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari);
        Cari.setBounds(250, 10, 72, 23);

        setSize(new java.awt.Dimension(772, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNilaiAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiAngkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiAngkaActionPerformed

    private void txtNilaiHurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiHurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiHurufActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        mahasiswa.setNIM(txtNIM.getText());
        mahasiswa.setNama(txtNama.getText());
        mahasiswa.setAlamat(txtAlamat.getText());
        mahasiswa.setTugas(Double.valueOf(txtNilaiTugas.getText()));
        mahasiswa.setUts(Double.valueOf(txtNilaiUts.getText()));
        mahasiswa.setUas(Double.valueOf(txtNilaiUas.getText()));
        txtNilaiAngka.setText(String.valueOf(mahasiswa.getNilaiAngka()));
        txtNilaiHuruf.setText(mahasiswa.getNilaiHuruf());
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNIM.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNilaiTugas.setText("");
        txtNilaiHuruf.setText("");
        txtNilaiUas.setText("");
        txtNilaiUts.setText("");
        txtNilaiAngka.setText("");
    }//GEN-LAST:event_btnClearActionPerformed
    
    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        MahasiswaNilai mhs = new MahasiswaNilai();
        mhs.setNIM(txtNIM.getText());
        mhs.setNama(txtNama.getText());
        mhs.setAlamat(txtAlamat.getText());
        mhs.setTugas(Double.parseDouble(txtNilaiTugas.getText()));
        mhs.setUts(Double.parseDouble(txtNilaiUts.getText()));
        mhs.setUas(Double.parseDouble(txtNilaiUas.getText()));
        String pesan = controller.insert(mhs);
        JOptionPane.showMessageDialog(this, pesan);
        tampilData();
    }//GEN-LAST:event_SimpanActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        tampilForm(txtNIM.getText());
    }//GEN-LAST:event_CariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiAngka;
    private javax.swing.JTextField txtNilaiHuruf;
    private javax.swing.JTextField txtNilaiTugas;
    private javax.swing.JTextField txtNilaiUas;
    private javax.swing.JTextField txtNilaiUts;
    // End of variables declaration//GEN-END:variables
    private void clear(){
        txtNIM.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNilaiTugas.setText("");
        txtNilaiHuruf.setText("");
        txtNilaiUas.setText("");
        txtNilaiUts.setText("");
        txtNilaiAngka.setText("");
    }
    

    private void tampilData() {
        MahasiswaNilai[] data = controller.getAll();
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        model.setRowCount(0);
        for (MahasiswaNilai mhs : data){
            Object[] row = {
                mhs.getNIM(),
                mhs.getNama(),
                mhs.getAlamat(),
                mhs.getTugas(),
                mhs.getUts(),
                mhs.getUas(),
                mhs.getNilaiAngka(),
                mhs.getNilaiHuruf()
            };
            model.addRow(row);
    }
    }

    private void tampilForm(String nim) {
        MahasiswaNilai mhs = controller.getByNIM(nim);
        if(mhs != null){
            txtNIM.setText(mhs.getNIM());
            txtNama.setText(mhs.getNama());
            txtAlamat.setText(mhs.getAlamat());
            txtNilaiTugas.setText(String.valueOf(mhs.getTugas()));
            txtNilaiUts.setText(String.valueOf(mhs.getUts()));
            txtNilaiUas.setText(String.valueOf(mhs.getUas()));
            txtNilaiAngka.setText(String.valueOf(mhs.getNilaiAngka()));
            txtNilaiHuruf.setText(mhs.getNilaiHuruf());
        }
    }
}

